# Generated by Django 4.0.3 on 2022-03-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gave',
            options={'verbose_name': 'give'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'statistic'},
        ),
        migrations.AlterModelOptions(
            name='took',
            options={'verbose_name': 'take'},
        ),
        migrations.AlterField(
            model_name='stats',
            name='gave',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stats',
            name='took',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
