# Generated by Django 4.0.3 on 2022-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_gave_options_alter_stats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('purpose', models.TextField()),
                ('dataTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='stats',
            name='expenses',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
